#!/usr/bin/perl

use strict;

use lib "../lib";
use Settings;
use Template;
use Utils;

use CGI qw(-debug :standard);
$CGI::DISABLE_UPLOADS = 1;

use vars qw($cgi);

$cgi = new CGI;

my $bgcolor = $cgi->param("bgc") or "ffffff";
my $fgcolor = $cgi->param("fgc") or "333333";


print $cgi->header();

my $html = Template::fillTemplateNew
  (
   Settings::settings("templateLib") . "/about.tmpl",
   {
    bgColor => $bgcolor,
    Color => $fgcolor,
    page_about => 1
   }
  );

print $html;
exit;
