#!/usr/bin/perl

use strict;

use lib "../lib";
use Database;
use Settings;
use Template;
use Utils;
use Colors;
use Cookie;

use CGI qw(-debug :standard);
$CGI::DISABLE_UPLOADS = 1;

use vars qw($cgi $db);

$cgi = new CGI;

$db = Database->new();
$db->connect(Settings::settings("dbName"));

my $uid;

unless($uid = Cookie::isUserLoggedIn($cgi, $db)) {
    print $cgi->header();
    print Utils::redirect(Settings::settings("loginURL") . "?redirect=" . Settings::settings("frontURL") . "2");
    exit;
}

my $perm = $db->getPermission($uid);
unless($perm == 1 || $perm == 2) {
    print $cgi->header();
    print Utils::message("you don't have permission.");
    exit;
}


if(defined($cgi->param("vote"))) {
    my $vote = $cgi->param("vote");

    #the vote type is the same as the person's permission.
    #0 = no permissions, 1 = normal tnq, 2 = super people.
    # Never really used above, there's only 1 vote type.
    $db->photoVote($vote, $uid, 1);
    print $cgi->header();
    print Utils::redirect(Settings::settings("frontURL") . "2");
    exit;
			  
}

print $cgi->header();

my %image;

$db->randomImage(\%image);
my @photographer = $db->getinfo($image{uid});
my $fn = $photographer[0];
my $ln = $photographer[1];

my $photogName = "$fn $ln";
#my $photogName = uc(substr($fn, 0, 1)) . substr($fn, 1) . " " . uc(substr($ln, 0, 1)) . substr($ln, 1);

my @time = Utils::sqlTime($image{time}, $image{offset});
my $tstring = "$time[0]:$time[1]:$time[2]";

my $caption = $db->getCaption($image{phid});

my @numphotos = $db->getinfo2($image{uid});

my @color = Colors::grabColor(Utils::imagePath(\%image, "small"));

my $wcolor = Utils::toWebColor(@color);

my $voteURL = Settings::settings("frontURL") . "2" . "?vote=" . $image{phid};

my $personURL = Settings::settings("timelineURL") . "?uid=" . $image{uid};

my $html = Template::fillTemplateNew
  (
   Settings::settings("templateLib") . "/front.tmpl",
  {
   Image => Utils::imageURL(\%image, "large"),
   personDay => $personURL,
   Caption => $caption,
   Time => $tstring,
   Photog => $photogName,
   NumPhotos => $numphotos[0],
   uid => $uid,
   Color => $wcolor,
   Phid => $image{phid},

   voteURL => $voteURL, # unused
  }
  );

print $html;
exit;
