#!/usr/bin/perl

use strict;

use lib "../lib";
use Database;
use Settings;
use Template;
use Utils;
use Colors;
use Cookie;

use CGI qw(-debug :standard);
$CGI::DISABLE_UPLOADS = 1;

use vars qw($cgi $db);

$cgi = new CGI;

$db = Database->new();
$db->connect(Settings::settings("dbName"));

my $uid = Cookie::isUserLoggedIn($cgi, $db);

print $cgi->header();

my %image;

$db->getRandomFrontPhoto(\%image);

my @photographer = $db->getinfo($image{uid});
my $fn = $photographer[0];
my $ln = $photographer[1];

my $photogName = lc($fn) . " " . lc($ln);
#my $photogName = uc(substr($fn, 0, 1)) . substr($fn, 1) . " " . uc(substr($ln, 0, 1)) . substr($ln, 1);

my ($width, $height) = Utils::imagesize(Utils::imagePath(\%image, "large"));

my @time = Utils::sqlTime($image{time});
my $tstring = "$time[0]:$time[1]:$time[2]";

my $caption = $db->getCaption($image{phid});

my @numphotos = $db->getinfo2($image{uid});



my @color = Colors::grabColor(Utils::imagePath(\%image, "small"));

my $lightness = Settings::settings("colorManipLightness");
my $sat = Settings::settings("colorManipSat");
my @bgColor = Colors::slightGray(@color, $lightness, $sat);

my $wbgcolor = Utils::toWebColor(@bgColor);
my $wcolor = Utils::toWebColor(@color);

my $aditlLeft = 550 - $width;

my $voteURL = Settings::settings("frontURL") . "?vote=" . $image{phid};

my $personURL = Settings::settings("timelineURL") . "?uid1=" . $image{uid};

my $loginURL = Settings::settings("loginURL")."?redirect=".Settings::settings("frontURL");
my $loginText = "login";
if ($uid) {
  $loginURL = Settings::settings("uploadURL");
  $loginText = "upload";
}

my $html = Template::fillTemplateNew
  (
   Settings::settings("templateLib") . "/front.tmpl",
  {
   Image => Utils::imageURL(\%image, "large"),
   Time => $tstring,
   Photog => $photogName,
   Color => $wcolor,
   bgColor => $wbgcolor,
   Width => $aditlLeft,
   Front => $voteURL, # unused
   RealWidth => $width - 8,
   Phid => $image{phid},
   NumPhotos => $numphotos[0],
   personDay => $personURL,
   Caption => $caption,
   urlLoginUpload => $loginURL,
   LoginUpload => $loginText,
  }
  );

print $html;
exit;
