#!/usr/bin/perl

use strict;

use lib "../lib";
use Database;
use Settings;
use Template;
use Utils;
use Colors;
use Cookie;

use CGI qw(-debug :standard);
$CGI::DISABLE_UPLOADS = 1;

use vars qw($cgi $db);

$cgi = new CGI;

$db = Database->new();
$db->connect(Settings::settings("dbName"));

my $uid;

unless($uid = Cookie::isUserLoggedIn($cgi, $db)) {
    print $cgi->header();
    print Utils::redirect(Settings::settings("loginURL") . "?redirect=" . Settings::settings("frontURL") . "2");
    exit;
}

my $perm = $db->getPermission($uid);
unless($perm == 1 || $perm == 2) {
    print $cgi->header();
    print Utils::message("you don't have permission.");
    exit;
}


if(defined($cgi->param("vote"))) {
    my $vote = $cgi->param("vote");

    #the vote type is the same as the person's permission.
    #0 = no permissions, 1 = normal tnq, 2 = super people.
    # Never really used above, there's only 1 vote type.
    $db->photoVote($vote, $uid, 1);
    print $cgi->header();
    print Utils::redirect(Settings::settings("frontURL") . "2");
    exit;
			  
}

print $cgi->header();

my %image;

$db->randomImage(\%image);
my @photographer = $db->getinfo($image{uid});
my $fn = $photographer[0];
my $ln = $photographer[1];

my $photogName = lc($fn) . " " . lc($ln);
#my $photogName = uc(substr($fn, 0, 1)) . substr($fn, 1) . " " . uc(substr($ln, 0, 1)) . substr($ln, 1);

my ($width, $height) = Utils::imagesize(Utils::imagePath(\%image, "large"));

my @time = Utils::sqlTime($image{time}, $image{offset});
my $tstring = "$time[0]:$time[1]:$time[2]";



my @color = Colors::grabColor(Utils::imagePath(\%image, "small"));
my $lightness = Settings::settings("colorManipLightness");
my $sat = Settings::settings("colorManipSat");
my @bgColor = Colors::slightGray(@color, $lightness, $sat);

my $wbgcolor = Utils::toWebColor(@bgColor);
my $wcolor = Utils::toWebColor(@color);

my $aditlLeft = 550 - $width;

my $voteURL = Settings::settings("frontURL") . "2" . "?vote=" . $image{phid};

my @vals = (Utils::imageURL(\%image, "large"), $tstring, $photogName, $wcolor, $wbgcolor,
	    $aditlLeft, $width, $voteURL);

my $html = Template::fillTemplate(Settings::settings("templateLib") . "/front2.html", \@vals);

print $html;
exit;
