#!/usr/bin/perl

use strict;

use lib "../lib";
use Database;
use Settings;
use Template;
use Utils;
use Colors;
use Cookie;

use CGI qw(-debug :standard);
$CGI::DISABLE_UPLOADS = 1;

use vars qw($cgi $db);

$cgi = new CGI;

$db = Database->new();
$db->connect(Settings::settings("dbName"));

my $start = $cgi->param("start");
if(defined($start)) {
    $start = int($start);
    if($start < 0 || $start > 1439 || !($start % 15 == 0)) {
	$start = 720;
    }
} else {
    $start = 720;
}
    
print $cgi->header();

my @initFrags;

push(@initFrags, $start);
push(@initFrags, Settings::settings("htmlFragmentURL") . "?uids=all");
push(@initFrags, Settings::settings("jsFragmentURL") . "?uids=all");

my $index = 1;


push(@initFrags, getNavlineContent());
push(@initFrags, navlineClickable());

my $html = Template::fillTemplate(Settings::settings("templateLib") . "/global-timeline.html", \@initFrags);

print $html;
exit;

sub getNavlineContent {

    my @allimages = $db->getAllPhotoInfoBetween(toSqlTime(0), toSqlTime(1439));

    my @bucketized;
    #takes only first image per bucket
    bucketize(\@allimages, \@bucketized);

    my $html = "";

    foreach(@bucketized) {
	my $xoff = getPixelOffset(0, $_->{time});
	$xoff = int($xoff / 3)*3;
	$html .= "<img alt=\"\" style=\"position:absolute; top:0px; left:" . $xoff . "px;\" src=\"" .
	    Utils::imageURL($_, "small") . "\" width=\"3\" height=\"10\"></img>\n";

    }

    return $html;
}

sub bucketize {
    my $listref = shift;
    my $outref = shift;

    my %buckets;

    foreach(@$listref) {
	my $xoff = getPixelOffset(0, $_->{time});
	my $bucket = int($xoff / 3);

	unless(exists($buckets{$bucket})) {
	    $buckets{$bucket} = 1;
	    push(@$outref, $_);
	}
    }
}

sub getPixelOffset {
    my $start = shift;
    my $time = shift;

    
    my @timel = Utils::sqlTime($time, 0);

    my $seconds = $timel[0]*3600 + $timel[1]*60 + $timel[2];

    # num of seconds into this fifteen minute window that we are.
    my $secondsOff = $seconds - ($start * 60);

    my $pixOff = int( ($secondsOff / 86400) * 792);
    
    return $pixOff;
}

sub toSqlTime {
    my $dayminute = shift;

    my $day = Settings::settings("eventDate");
    my $hour = int($dayminute / 60);
    my $minute = $dayminute % 60;
    
    return "$day $hour:$minute:00";
}

sub navlineClickable {

    my $html = "";
    for(my $i = 0; $i < 24; $i++) {
	my $min = $i * 60;
	my $off = 33 * $i;
	$html .= "<div style=\"z-index:3; position:absolute; top:-40px; left:" . $off . "px;\">";
	$html .= "<a class=\"navclick\" href=\"#\" onclick=\"gotoTime($min)\"></a></div>\n";
    }
    return $html;
}
