#!/usr/bin/perl

use strict;

use lib "../lib";
use Database;
use Settings;
use Template;
use Colors;
use Utils;
use Cookie;

use CGI qw(-debug :standard);
$CGI::DISABLE_UPLOADS = 1;

use vars qw($cgi $db);

$cgi = new CGI;

my $doedit = $cgi->param("editcaption");

$db = Database->new();
$db->connect(Settings::settings("dbName"));

print $cgi->header();

my $visitoruid = Cookie::isUserLoggedIn($cgi, $db);

my %image;
my $phid = $cgi->param("phid");

$phid = int($phid);

$db->photoInfo($phid, \%image);

my $setcaption = $cgi->param("setcaption");
if($setcaption && $visitoruid == $image{uid}) {
    my $caption = $cgi->param("caption");
    $db->setCaption($phid, $caption);
}


my @photographer = $db->getinfo($image{uid});
my $fn = $photographer[0];
my $ln = $photographer[1];

my $photogName = "$fn $ln";

my @time = Utils::sqlTime($image{time});
my $tstring = "$time[0]:$time[1]:$time[2]";

my @numphotos = $db->getinfo2($image{uid});


my @color = Colors::grabColor(Utils::imagePath(\%image, "small"));

my ($wcolor, $wbgcolor) = Utils::getWebColors(Utils::imagePath(\%image, "small"));

my $personURL = Settings::settings("timelineURL") . "?uid=" . $image{uid};

my $caption = $db->getCaption($image{phid});

my $prev = $db->getPreviousPhoto($image{uid}, $image{phid});
my $next = $db->getNextPhoto($image{uid}, $image{phid});

my $html = Template::fillTemplateNew
  (
   Settings::settings("templateLib") . "/front.tmpl",
  {
   Image => Utils::imageURL(\%image, "large"),
   personDay => $personURL,
   Caption => $caption,
   EditCaption => $doedit,
   CanEditCaption => ($visitoruid == $image{uid} && !$doedit),
   Time => $tstring,
   Photog => $photogName,
   NumPhotos => $numphotos[0],
   uid => $visitoruid,
   Color => $wcolor,
   bgColor => $wbgcolor,
   Phid => $image{phid},

   prev => $prev,
   next => $next,

   voteURL => undef, # unused
  }
  );

print $html;
exit;




