#!/usr/bin/perl

use strict;

use lib "../lib";
use Database;
use Settings;
use Template;
use Utils;
use Cookie;

#good random seed. from programming perl.
#srand ( time() ^ ($$ + ($$ << 15)) ); 

use HTML::Entities;
use CGI qw(-debug :standard);
$CGI::DISABLE_UPLOADS = 1;

use vars qw($cgi $db);

$cgi = new CGI;

$db = Database->new();
$db->connect(Settings::settings("dbName"));

my $visitoruid = Cookie::isUserLoggedIn($cgi, $db);

my $majorid = $cgi->param("majorid");

unless(defined($majorid)) {
    $majorid = 0;
}

my @users = $db->userInfoWithPhotos();

if($cgi->param("random")) {
    selectRandom(\@users, $cgi);
    exit;
}

my @sorted;
Utils::alphaSplitList(1, \@users, \@sorted);

@sorted = @{$sorted[0]}; #see alphaSplitlist

my @subsorted;
majorList($majorid, \@sorted, \@subsorted);

my $barcodeBase = Settings::settings("tinyBarcodeURL");

my @users;

foreach my $user (@subsorted) {
  my $uid = $user->{uid};
  my $barcode = $barcodeBase . "/" . $uid . "\.jpg";

  my $name = encode_entities($user->{fn}) . " "
      . encode_entities(substr($user->{ln}, 0, 1))
      ."<wbr>"
      . encode_entities(substr($user->{ln}, 1));

  my $url = Settings::settings("timelineURL") . "?uid=" . $uid;

  my @num = $db->getinfo2($uid);

  push @users, 
    {
     uid => $uid,
     barcode => $barcode,
     name => $name,
     url => $url,
     numphotos => $num[0],
    };

}

print $cgi->header();
my $html = Template::fillTemplateNew
  (
   Settings::settings("templateLib") . "/select-user.tmpl",
   {
    page_select_user => 1,
    "majorid_$majorid", 1,

    users => \@users,
    uid => $visitoruid,
   }
  );

print $html;
exit;


#sublist within a letter range
sub majorList {
    my $id = shift;
    my $inref = shift;
    my $outref = shift;

    my @starts = ("a", "f", "j", "o", "t");
    my @ends = ("e", "i", "n", "s", "z");

    my $start = $starts[$id];
    my $end = $ends[$id];

    foreach(@$inref) {
	if(substr($_->{name}, 0, 1) ge $start && substr($_->{name}, 0, 1) le $end) {
	    push(@$outref, $_);
	}
    }
}

sub selectRandom() {
    my $uids = shift;
    my $cgi = shift;

    my @uids = $db->randomUsersWithPhotos(1);

    my $url = Settings::settings("timelineURL");

    $url .= "?uid=" . $uids[0];

    print $cgi->header();
    print Utils::redirect($url);
}
